INHERIT: ../../base.yml
site_name: "合宙文档中心"

site_url: https://docs.openluat.com/air724ug/at/

meta:
  model: "air724ug"
  doctp : "at"

nav:
  #- 首页: index.md
  - 快速入门:
    - 介绍: quick_start/index.md
    - TCP快速入门: quick_start/tcp/tcp.md
    - MQTT快速入门: quick_start/mqtt.md
    - HTTP快速入门: quick_start/http.md
  - 硬件指南:
    - 典型硬件设计指南:
      - 简介: hardware/design/index.md
      - 典型应用参考设计: hardware/design/reference.md
      - 开机启动及外围电路: hardware/design/poweron.md
      - 供电设计及选型推荐: hardware/design/power.md
      - 串口电路设计指导: hardware/design/uart.md
      - SIM卡电路设计指导: hardware/design/sim.md
      #- LED状态灯电路: hardware/design/led.md
      - 天线电路设计指导: hardware/design/ant.md
      #- 常见供电电路: ../luatos/hardware/design/power 直接引用存在一个问题，左边导航栏会跳转到LuatOS资料中心，阅读体验很差
      #- 常见供电电路: hardware/design/power.md
      #- 常见充电电路: hardware/design/charge.md
      #- 常见开机电路: hardware/design/poweron.md
      #- 常见关机电路: hardware/design/poweroff.md
      #- Reset电路: hardware/design/reset.md
      #- 看门狗电路: hardware/design/wdt.md
      #- SIM卡电路: hardware/design/sim.md
      #- 天线电路: hardware/design/ant.md
      #- UART 0调试电路: hardware/design/uart0.md
      #- UART 1通信电路: hardware/design/uart1.md
      #- UART 2通信电路: hardware/design/uart2.md
      #- USB通信电路: hardware/design/usb.md
      #- LED状态灯电路: hardware/design/led.md
      #- 模组休眠唤醒电路: hardware/design/sleep.md
      #- 模组唤醒休眠状态下的主控电路: hardware/design/wakeup.md
      #- 模组控制外设的电路: hardware/design/ctrl.md
      #- 外设触发模组中断的电路: hardware/design/int.md
      #- 测试点电路: hardware/design/check_point.md
      #- 温湿度传感器参考电路: hardware/design/sensor.md
      #- 远程空开参考电路: hardware/design/remote.md
  - 软件指南:
    - 介绍: app/index.md
    - AT指令手册: app/at_command.md
    - 应用实例:
      - 简介: app/command/index.md
      - TCP: app/command/tcp/index.md
      - UDP: app/command/udp/index.md
      - MQTT: app/command/mqtt/index.md
      - HTTP: app/command/http/index.md
      - FTP: app/command/ftp/index.md
      - NTP: app/command/ntp/index.md
      - 阿里云: app/command/aliiot/index.md
      - 腾讯云: app/command/tencentiot/index.md
      - 百度云: app/command/baiduiot/index.md
      - ONENET: app/command/onenet/index.md
      - 华为云: app/command/huaweiiot/index.md
      - 电信云: app/command/wingiot/index.md
      - 低功耗: app/command/lowpower/index.md
      - 文件系统: app/command/fs/index.md
      - 音频控制: app/command/audio/index.md
      - 短消息(SMS): app/command/sms/index.md
      - 通话(VoLTE): app/command/volte/index.md
      - 基站&WIFI定位: app/command/lbswifi/index.md
      - 远程升级(FOTA): app/command/fota/index.md
    - 常用状态机:
      - 网络状态机: app/state/network/index.md
      - TCP状态机: app/state/tcp/index.md
      - MQTT状态机: app/state/mqtt/index.md
    - 常见异常:
      - 网络异常类: app/error/network/index.md
      - 通信异常类: app/error/command/index.md
    - MCU实例代码:
      - STM32演示代码: app/mcu/stm32/index.md
  - 固件版本: firmware.md
  - 常见问题: faq.md
  - DTU: https://docs.openluat.com/dtu/
  - 增值服务: https://docs.openluat.com/web/
  - 技术博客: https://docs.openluat.com/blog/
  - 问答中心: https://chat.openluat.com/
  - 合宙官网: https://www.openluat.com/
  - 文档共建: https://docs.openluat.com/askforhelp/
