site_name: 合宙Cat.1模块AT指令手册
nav:
  - 首页: index.md
  - Air780E: 780E/index.md
  - Air780EP: 780EP/index.md
  - Air780EQ: AT_Commands_Debug.md
  - Air700ECQ: AT_Commands_Other.md
  - Air700EAQ: index.md
