INHERIT: ../../base.yml
site_name: "合宙文档中心"
site_url: https://docs.openluat.com/air780e/luatos/

meta:
  model: "air780e"
  doctp : "luatos"
nav:
  - 快速入门:
    - 介绍: quick_start/index.md
    - HelloWorld教程: quick_start/hello/index.md
    - 本地脚本控制灯的亮和灭: quick_start/led/index.md
    - 电脑浏览器通过Air780E控制灯的亮和灭: quick_start/netled/index.md
    - 采集温湿度数据并上传到网页查看: quick_start/nettemp/index.md
    - 固件的远程升级: quick_start/upgrade/index.md
    - 通过MQTT连接实现远程控制: quick_start/mqtt/index.md
    #- 驱动SPI小屏幕的详细讲解: quick_start/lcd/index.md
    - 使用文件系统存储温湿度数据: quick_start/file/index.md
    - 500毫安的电池让Air780E续航10年: quick_start/battery/index.md
    - Air780E 跟服务器之间的加密通信: quick_start/ssl/index.md
    - Air780E怎么获取精准的时钟: quick_start/time/index.md
  - 硬件指南:
    - 典型硬件设计指南:
      - 简介: hardware/design/index.md
      #- 常见供电电路: ../luatos/hardware/design/power 直接引用存在一个问题，左边导航栏会跳转到LuatOS资料中心，阅读体验很差
      - 典型应用参考设计: hardware/design/reference.md
      - 开机启动及外围电路: hardware/design/poweron.md
      - 供电设计及选型推荐: hardware/design/power.md
      - SIM卡电路设计指导: hardware/design/sim.md
      - 串口电路设计指导: hardware/design/uart.md
      #- USB电路设计指导: hardware/design/usb.md
      - GPIO使用注意事项: hardware/design/gpio.md
      - ADC/LED/I2C/SPI/USB: hardware/design/adcledi2cspiusb.md
      - 天线电路设计指导: hardware/design/ant.md
      #- 串口电路设计指导: hardware/design/uart.md
      #- LED状态灯电路: hardware/design/led.md
      #- 常见供电电路: hardware/design/power.md
      #- 常见充电电路: hardware/design/charge.md
      #- 常见开机电路: hardware/design/poweron.md
      #- 常见关机电路: hardware/design/poweroff.md
      #- Reset电路: hardware/design/reset.md
      #- 看门狗电路: hardware/design/wdt.md
      #- UART 0调试电路: hardware/design/uart0.md
      #- UART 1通信电路: hardware/design/uart1.md
      #- UART 2通信电路: hardware/design/uart2.md
      #- 模组休眠唤醒电路: hardware/design/sleep.md
      #- 模组唤醒休眠状态下的主控电路: hardware/design/wakeup.md
      #- 模组控制外设的电路: hardware/design/ctrl.md
      #- 外设触发模组中断的电路: hardware/design/int.md
      #- 测试点电路: hardware/design/check_point.md
      #- 温湿度传感器参考电路: hardware/design/sensor.md
      #- 远程空开参考电路: hardware/design/remote.md
  - 软件指南:
    - 介绍: app/index.md
    - 硬件驱动:
      - 简介: app/driver/index.md
      - UART: 
        - 简介: app/driver/uart/index.md
        - 硬件准备: app/driver/uart/01.md
        - 基本用法: app/driver/uart/basic.md
        - RS485通信: app/driver/uart/rs485.md
        - USB虚拟串口: app/driver/uart/usb_uart.md
        - 多串口: app/driver/uart/uarts.md
        - 低功耗唤醒: app/driver/uart/uart_pm.md
        - TCP-UART透传: app/driver/uart/uart_tcp.md
        - MQTT-UART透传: app/driver/uart/uart_mqtt.md
        - UDP-UART透传: app/driver/uart/uart_udp.md
        - WebSocket-UART透传: app/driver/uart/uart_ws.md
        - UART2复用到另外一组管脚: app/driver/uart/uart_mux.md
        - UART电平: app/driver/uart/uart_level.md
        - 总结: app/driver/uart/summary.md
        - 常见问题: app/driver/uart/faq.md
        - 扩展: app/driver/uart/ext.md
      - ADC: app/driver/adc/index.md
      - GPIO:
        - 简介: app/driver/gpio/index.md
        - 硬件准备: app/driver/gpio/01.md
        - 基本用法: app/driver/gpio/basic.md
        - 输入模式: app/driver/gpio/input.md
        - 输出模式: app/driver/gpio/output.md
        - 中断模式: app/driver/gpio/interrupt.md
        - IO复用: app/driver/gpio/iomux.md
        - 上拉下拉: app/driver/gpio/pull.md
        - 开漏模式: app/driver/gpio/open_drain.md
        - 常驻GPIO: app/driver/gpio/retention.md
        - IO翻转速度: app/driver/gpio/speed.md
        - 总结: app/driver/gpio/summary.md
        - 常见问题: app/driver/gpio/faq.md
        - 扩展: app/driver/gpio/ext.md
      - I2C: app/driver/i2c/index.md
      - SPI: app/driver/spi/index.md
      - PWM: app/driver/pwm/index.md
    - 网络驱动(Socket):
      - 简介: app/socket/index.md
      - TCP: app/socket/tcp/index.md
      - UDP: app/socket/udp/index.md
      - HTTP: app/socket/http/index.md
      - MQTT: app/socket/mqtt/index.md      
      - FTP: app/socket/ftp/index.md
      - NTP: app/socket/ntp/index.md
      - WebSocket: app/socket/websocket/index.md
    - 网络应用:
      - 简介: app/netapp/index.md
      - 阿里云: app/netapp/aliiot/index.md
      - 腾讯云: app/netapp/tencentiot/index.md
      - ONENET: app/netapp/onenet/index.md
      - 百度云: app/netapp/baiduiot/index.md
      - 华为云: app/netapp/huaweiiot/index.md
      - 涂鸦云: app/netapp/tuyaiot/index.md
      - errDump: app/netapp/errdump/index.md
      - FOTA升级: app/netapp/fota/index.md
      - 基站WIFI定位: app/netapp/lbswifi/index.md
    - 基础服务:
      - 简介: app/service/index.md
      - LuatOS运行框架: app/service/framework/index.md
      - 文件系统(io): app/service/fs/index.md
      - 键值对存储(fskv): app/service/fskv/index.md
      - 定时器(timer): app/service/timer/index.md
      - 位运算(bit): app/service/bit/index.md
      - 随机数(random): app/service/random/index.md
      - 模块信息(hmeta): app/service/module/index.md
      - 内部硬件看门狗(wdt): app/service/wdt/index.md
    - 4G通信:
      - 简介: app/mobile/index.md
      - 通信信息(mobile): app/mobile/info/index.md
      - 短消息(sms): app/mobile/sms/index.md
    - 功耗管理:
      - 简介: app/power/index.md
      - 低功耗: app/power/sleep/index.md
    - 通用工具库:
      - 简介: app/utils/index.md
      - 数据格式转换: app/utils/dataconvert/index.md
      - json数据处理: app/utils/json/index.md
      - 字符串处理: app/utils/string/index.md
      - 日志输出: app/utils/log/index.md
      - 数据打包解包(pack): app/utils/pack/index.md
      - 通用加解密函数(crypto): app/utils/crypto/index.md
      - protobuf数据处理: app/utils/protobuf/index.md
      - 64位数据处理: app/utils/64bit/index.md
      - iconv字符集转换: app/utils/iconv/index.md
      - C语言内存数组(zbuff): app/utils/zbuff/index.md
      - zlib解压: app/utils/zlib/index.md
  - SDK&Demo: firmware.md
  - API文档:
    - 索引页: api/index.md
    - 核心库: api/core/index.md
    - 扩展库: api/ext/index.md
  - 常见问题: faq.md
  - DTU: https://docs.openluat.com/dtu/
  - 增值服务: https://docs.openluat.com/web/
  - 技术博客: https://docs.openluat.com/blog/
  - 问答中心: https://chat.openluat.com/
  - 合宙官网: https://www.openluat.com/
  - 文档共建: https://docs.openluat.com/askforhelp/
