INHERIT: ../../base.yml
site_name: "合宙文档中心"
site_url: https://docs.openluat.com/air201/luatos/

meta:
  model: "air201"
  doctp : "luatos"
nav:
  - 快速入门: 
    - 简介: quickstart/index.md
    - hello world教程: quickstart/hello.md
    - 本地脚本控制灯的亮和灭: quickstart/led.md
    - 用电脑浏览器通过Air201控制灯的亮和灭: quickstart/led_web.md
    - 定位功能: quickstart/gnss.md
    - I2C驱动ATH10温湿度传感器: quickstart/i2c_ath10.md
    - PWRKEY按键控制: quickstart/pwrkey.md
    - fota升级(远程升级): quickstart/fota.md
    - 文件系统: quickstart/fs.md
    - 录音和播放: quickstart/record.md
    - MQTT: quickstart/mqtt.md
    - g-sensor传感器: quickstart/gsensor.md
    - RTC: quickstart/rtc.md
    - uart: quickstart/uart.md
    - camera: quickstart/camera.md
  - 硬件资料: 
    - 产品介绍: hardware/index.md
    - 模块及芯片: hardware/module.md
    - 支持频段: hardware/bands.md
    - 产品特性: hardware/feature.md
    - 硬件说明:
      - 简介: hardware/design/index.md
      - USB Boot烧录: hardware/design/usb_boot.md
      - BTB扩展接口: hardware/design/btb.md
      - 休眠: hardware/design/sleep.md
      - 4G天线调试: hardware/design/4g_ant.md
      - GNSS天线调试: hardware/design/gnss_ant.md
      - 设计音频注意事项: hardware/design/audio.md
      - 调试音频方法: hardware/design/audio_debug.md
  - 软件指南:
    - 介绍: app/index.md
    - 硬件驱动:
      - 简介: app/driver/index.md
    - 网络驱动(Socket):
      - 简介: app/socket/index.md
    - 网络应用:
      - 简介: app/netapp/index.md
    - 基础服务:
      - 简介: app/service/index.md
    - 4G通信:
      - 简介: app/mobile/index.md
    - 功耗管理:
      - 简介: app/power/index.md
    - 通用工具库:
      - 简介: app/utils/index.md
  - SDK&Demo: firmware.md
  - API文档:
    - 索引页: api/index.md
    - 核心库: api/core/index.md
    - 扩展库: api/ext/index.md
  - 常见问题: faq.md
  - DTU: https://docs.openluat.com/dtu/
  - 增值服务: https://docs.openluat.com/web/
  - 技术博客: https://docs.openluat.com/blog/
  - 问答中心: https://chat.openluat.com/
  - 合宙官网: https://www.openluat.com/
  - 文档共建: https://docs.openluat.com/askforhelp/
