INHERIT: ../../base.yml
site_name: "合宙文档中心"
site_url: https://docs.openluat.com/air780eg/luatos/

meta:
  model: "air780eg"
  doctp : "luatos"
nav:
  - 快速入门:
    - 介绍: quick_start/index.md
  - 软件demo:
    - 介绍: app/index.md
  - 硬件demo:
    - 典型硬件设计指南:
      - 简介: hardware/design/index.md
  - 固件版本: firmware.md
  - 常见问题: faq.md
  - 卫星定位模组: https://docs.openluat.com/gnss/
  - DTU: https://docs.openluat.com/dtu/
  - 增值服务: https://docs.openluat.com/web/
  - 问答中心: https://chat.openluat.com/
  - 合宙官网: https://www.openluat.com/
