INHERIT: ../../base.yml
site_name: "合宙文档中心"
site_url: https://docs.openluat.com/air724ug/luatos/

meta:
  model: "air724ug"
  doctp : "luatos"
nav:
  - 快速入门:
    - 介绍: quick_start/index.md
    - HelloWorld教程:
      - 介绍: quick_start/hello/index.md    
  - 硬件指南:
    - 典型硬件设计指南:
      - 简介: hardware/design/index.md
  - 软件指南:
    - 介绍: app/index.md
    - 硬件驱动:
      - 简介: app/driver/index.md
      - UART: app/driver/uart/index.md
      - ADC: app/driver/adc/index.md
      - GPIO: app/driver/gpio/index.md
      - I2C: app/driver/i2c/index.md
      - SPI: app/driver/spi/index.md
      - PWM: app/driver/pwm/index.md
      - KEYPAD: app/driver/keypad/index.md
      - SD卡: app/driver/sd/index.md
      - 蓝牙: app/driver/bluetooth/index.md
    - 网络驱动(Socket):
      - 简介: app/socket/index.md
      - TCP: app/socket/tcp/index.md
      - UDP: app/socket/udp/index.md
      - HTTP: app/socket/http/index.md
      - MQTT: app/socket/mqtt/index.md      
      - FTP: app/socket/ftp/index.md
      - NTP: app/socket/ntp/index.md
      - WebSocket: app/socket/websocket/index.md
    - 网络应用:
      - 简介: app/netapp/index.md
      - 阿里云: app/netapp/aliiot/index.md
      - 腾讯云: app/netapp/tencentiot/index.md
      - ONENET: app/netapp/onenet/index.md
      - 百度云: app/netapp/baiduiot/index.md
      - 华为云: app/netapp/huaweiiot/index.md
      - errDump: app/netapp/errdump/index.md
      - FOTA升级: app/netapp/fota/index.md
      - 基站WIFI定位: app/netapp/lbswifi/index.md
    - 基础服务:
      - 简介: app/service/index.md
      - LuatOS运行框架: app/service/framework/index.md
      - 文件系统(io): app/service/fs/index.md
      - 键值对存储(nvm): app/service/nvm/index.md
      - 定时器(timer): app/service/timer/index.md
      - 闹钟(alarm): app/service/alarm/index.md
      - 位运算(bit): app/service/bit/index.md
      - 随机数(random): app/service/random/index.md
      - 外部硬件看门狗(wdt): app/service/wdt/index.md
    - 4G通信:
      - 简介: app/mobile/index.md
      - 短消息(sms): app/mobile/sms/index.md
    - 功耗管理:
      - 简介: app/power/index.md
      - 低功耗: app/power/sleep/index.md
    - 通用工具库:
      - 简介: app/utils/index.md
      - 数据格式转换: app/utils/dataconvert/index.md
      - json数据处理: app/utils/json/index.md
      - 字符串处理: app/utils/string/index.md
      - 日志输出: app/utils/log/index.md
      - 数据打包解包(pack): app/utils/pack/index.md
      - 通用加解密函数(crypto): app/utils/crypto/index.md
      - protobuf数据处理: app/utils/protobuf/index.md
      - iconv字符集转换: app/utils/iconv/index.md
  - SDK&Demo: firmware.md
  - 常见问题: faq.md
  - DTU: https://docs.openluat.com/dtu/
  - 增值服务: https://docs.openluat.com/web/
  - 技术博客: https://docs.openluat.com/blog/
  - 问答中心: https://chat.openluat.com/
  - 合宙官网: https://www.openluat.com/
  - 文档共建: https://docs.openluat.com/askforhelp/
