INHERIT: ../../base.yml
site_name: "合宙文档中心"
site_url: https://docs.openluat.com/air724ug/luatos/

meta:
  model: "air724ug"
  doctp : "luatos"
nav:
  - 产品手册: quickstart/index.md
  - 常见问题: faq.md
  - 卫星定位模组: https://docs.openluat.com/gnss/
  - DTU: https://irtu.cn/
  - 卫星定位模组: https://docs.openluat.com/web/
  - 问答中心: https://chat.openluat.com/
  - 合宙官网: https://www.openluat.com/
