INHERIT: ../../base.yml
site_name: "合宙文档中心"

site_url: https://docs.openluat.com/air700eaq/at/

meta:
  model: "air700eaq"
  doctp : "at"

nav:
  - 首页: index.md
  - 快速开始: quick_start.md
  - AT指令:
    - AT介绍: 
      - 完整指令手册: at_command.md
    - 应用实例:
      - 连接TCP服务器: app/tcp.md
      - 连接MQTT服务器: app/mqtt.md
      - 访问HTTP地址: app/http.md
    - MCU实例代码:
      - STM32演示代码: mcu/stm32.md
      - Air32演示代码: mcu/air32.md
    - 常用状态机:
      - TCP状态机: state/tcp.md
      - MQTT状态机: state/mqtt.md
      - 网络状态机: state/network.md
    - 常见异常:
      - 网络异常类: error/network.md
      - 通信异常类: error/error.md
  - 固件下载: firmware.md
  - 常见问题: faq.md
  - 卫星定位模组: https://docs.openluat.com/gnss/
  - DTU: https://irtu.cn/
  - 卫星定位模组: https://docs.openluat.com/web/
  - 问答中心: https://chat.openluat.com/
  - 合宙官网: https://www.openluat.com/

