INHERIT: ../../base.yml
site_name: "合宙文档中心"
site_url: https://docs.openluat.com/air700emq/luatos/

meta:
  model: "air700emq"
  doctp : "luatos"
nav:
  - 快速入门:
    - 介绍: quick_start/index.md
  - 软件指南:
    - 介绍: app/index.md
  - 硬件指南:
    - 典型硬件设计指南:
      - 简介: hardware/design/index.md
      - 典型应用参考设计: hardware/design/reference.md
      - 开机启动及外围电路: hardware/design/poweron.md
      - 供电设计及选型推荐: hardware/design/power.md
      - SIM卡电路设计指导: hardware/design/sim.md
      #- USB电路设计指导: hardware/design/usb.md
      - GPIO使用注意事项: hardware/design/gpio.md
      - 天线电路设计指导: hardware/design/ant.md
      #- 串口电路设计指导: hardware/design/uart.md
  - SDK&Demo: firmware.md
  - 常见问题: faq.md
  - DTU: https://docs.openluat.com/dtu/
  - 增值服务: https://docs.openluat.com/web/
  - 技术博客: https://docs.openluat.com/blog/
  - 问答中心: https://chat.openluat.com/
  - 合宙官网: https://www.openluat.com/
  - 文档共建: https://docs.openluat.com/askforhelp/
