INHERIT: ../base.yml
site_name: 合宙模组资料中心

meta:
  author: 上海合宙通信科技有限公司

nav:
  - 选型手册: product.md
  - Air780E:
    - 简介: air780e/index.md
    - 产品手册: air780e/product/index.md
    - LuatOS资料: https://docs.openluat.com/air780e/luatos/
    - AT资料: https://docs.openluat.com/air780e/at/
  - Air700:
    - 简介: air700/index.md
    - Air700ECQ资料:
      - 简介: air700ecq/index.md
      - 产品手册: air700ecq/product/index.md
      - LuatOS资料: https://docs.openluat.com/air700ecq/luatos/
      - AT资料: https://docs.openluat.com/air700ecq/at/
    - Air700EMQ资料:
      - 简介: air700emq/index.md
      - 产品手册: air700emq/product/index.md
      - LuatOS资料: https://docs.openluat.com/air700emq/luatos/
      - AT资料: https://docs.openluat.com/air700emq/at/
    - Air700EAQ资料:
      - 简介: air700eaq/index.md
      - 产品手册: air700eaq/product/index.md
      - LuatOS资料: https://docs.openluat.com/air700eaq/luatos/
      - AT资料: https://docs.openluat.com/air700eaq/at/
  - Air780EQ:
    - 简介: air780eq/index.md
    - 产品手册: air780eq/product/index.md
    - LuatOS资料: https://docs.openluat.com/air780eq/luatos/
    - AT资料: https://docs.openluat.com/air780eq/at/
  - Air780EP:
    - 简介: air780ep/index.md
    - 产品手册: air780ep/product/index.md
    - LuatOS资料: https://docs.openluat.com/air780ep/luatos/
    - AT资料: https://docs.openluat.com/air780ep/at/
  - Air780EPS:
    - 简介: air780eps/index.md
    - 产品手册: air780eps/product/index.md
    - LuatOS资料: https://docs.openluat.com/air780eps/luatos/
    - AT资料: https://docs.openluat.com/air780eps/at/
  - Air780EX:
    - 简介: air780ex/index.md
    - 产品手册: air780ex/product/index.md
    - LuatOS资料: https://docs.openluat.com/air780ex/luatos/
    - AT资料: https://docs.openluat.com/air780ex/at/
  - Air724UG:
    - 简介: air724ug/index.md
    - 产品手册: air724ug/product/index.md
    - LuatOS资料: https://docs.openluat.com/air724ug/luatos/
    - AT资料: https://docs.openluat.com/air724ug/at/
  - Air201:
    - 简介: air201/index.md
    - 产品手册: air201/product/index.md
    - LuatOS资料: https://docs.openluat.com/air201/luatos/
  - Air780EG:
    - 简介: air780eg/index.md
    - 产品手册: air780eg/product/index.md
    - LuatOS资料: https://docs.openluat.com/air780eg/luatos/
    - AT资料: https://docs.openluat.com/air780eg/at/
  - 卫星定位模组: gnss.md
  - DTU: https://irtu.cn/
  - 增值服务: web.md
  - 技术博客: https://docs.openluat.com/blog/
  - 问答中心: https://chat.openluat.com/
  - 官网: https://www.openluat.com/
  - 文档共建: askforhelp.md

