INHERIT: ../base.yml
site_name: 合宙模组资料中心

meta:
  author: 上海合宙通信科技有限公司

nav:
  - 产品手册: product.md
  - Air780E:
    - 简介: air780e/index.md
    - LuatOS资料: https://docs.openluat.com/air780e/luatos/
    - AT资料: https://docs.openluat.com/air780e/at/
  - Air700:
    - 简介: air700/index.md
    - Air700ECQ的LuatOS资料: https://docs.openluat.com/air700ecq/luatos/
    - Air700EAQ的LuatOS资料: https://docs.openluat.com/air700eaq/luatos/
    - Air700EMQ的LuatOS资料: https://docs.openluat.com/air700emq/luatos/
    - Air700ECQ的AT资料: https://docs.openluat.com/air700ecq/at/
    - Air700EAQ的AT资料: https://docs.openluat.com/air700eaq/at/
    - Air700EMQ的AT资料: https://docs.openluat.com/air700emq/at/
  - Air780EQ:
    - 简介: air780eq/index.md
    - LuatOS资料: https://docs.openluat.com/air780eq/luatos/
    - AT资料: https://docs.openluat.com/air780eq/at/
  - Air780EP:
    - 简介: air780ep/index.md
    - LuatOS资料: https://docs.openluat.com/air780ep/luatos/
    - AT资料: https://docs.openluat.com/air780ep/at/
  - Air780EPS:
    - 简介: air780eps/index.md
    - LuatOS资料: https://docs.openluat.com/air780eps/luatos/
    - AT资料: https://docs.openluat.com/air780eps/at/
  - Air780EX:
    - 简介: air780ex/index.md
    - LuatOS资料: https://docs.openluat.com/air780ex/luatos/
    - AT资料: https://docs.openluat.com/air780ex/at/
  - Air724UG:
    - 简介: air724ug/index.md
    - LuatOS资料: https://docs.openluat.com/air724ug/luatos/
    - AT资料: https://docs.openluat.com/air724ug/at/
  - Air201:
    - 简介: air201/index.md
    - LuatOS资料: https://e3zt58hesn.feishu.cn/wiki/DfMMw2ZFziqPIikh1BMcZDwHnCb
  - Air780EG:
    - 简介: air780eg/index.md
    - LuatOS资料: https://docs.openluat.com/air780eg/luatos/
    - AT资料: https://docs.openluat.com/air780eg/at/
  - 卫星定位模组: gnss.md
  - DTU: https://irtu.cn/
  - 增值服务: web.md
  - 技术博客: https://docs.openluat.com/blog/
  - 问答中心: https://chat.openluat.com/
  - 官网: https://www.openluat.com/
  - 文档共建: askforhelp.md

