INHERIT: ../base.yml
site_name: 合宙模组资料中心

meta:
  author: 上海合宙通信科技有限公司

nav:
  - 必看资料: 
    - 选型指南: product.md
    - Luatools教程和下载: 
      - 1，下载与安装: Luatools_1.md
      - 2，主要文件夹介绍: Luatools_2.md
      - 3，菜单和界面介绍: Luatools_3.md      
      - 4，日志查看: Luatools_4.md
      - 5，项目管理: Luatools_5.md
      - 6，固件烧录: Luatools_6.md          
    - 各个型号功耗对比:
      - 1，实时在线的各模组功耗数据: tcppower.md
      - 2，低频次的各模组功耗数据:   psmpower.md
    - LuatOS 入门教程:  
      - Lua语法基础教程: lua_lesson.md
      - LuatOS基础教程: luatOS.md
      - LuatOS-Air教程: luatOS_Air.md
    - 模组底层日志调试教程:  epat_lesson.md
    - 量产多路下载工具介绍:  multi_download.md
    - TCPUDP_Web测试工具:   TCPUDP_Test.md
    - 远程固件升级服务:   fota_lesson.md
  - Air780E:
    - 简介: air780e/index.md
    - 产品手册: air780e/product/index.md
    - LuatOS资料: https://docs.openluat.com/air780e/luatos/
    - AT资料: https://docs.openluat.com/air780e/at/
  - Air700:
    - 简介: air700/index.md
    - Air700ECQ资料:
      - 简介: air700ecq/index.md
      - 产品手册: air700ecq/product/index.md
      - LuatOS资料: https://docs.openluat.com/air700ecq/luatos/
      - AT资料: https://docs.openluat.com/air700ecq/at/
    - Air700EMQ资料:
      - 简介: air700emq/index.md
      - 产品手册: air700emq/product/index.md
      - LuatOS资料: https://docs.openluat.com/air700emq/luatos/
      - AT资料: https://docs.openluat.com/air700emq/at/
    - Air700EAQ资料:
      - 简介: air700eaq/index.md
      - 产品手册: air700eaq/product/index.md
      - LuatOS资料: https://docs.openluat.com/air700eaq/luatos/
      - AT资料: https://docs.openluat.com/air700eaq/at/
  - Air780EQ:
    - 简介: air780eq/index.md
    - 产品手册: air780eq/product/index.md
    - LuatOS资料: https://docs.openluat.com/air780eq/luatos/
    - AT资料: https://docs.openluat.com/air780eq/at/
  - Air780EP:
    - 简介: air780ep/index.md
    - 产品手册: air780ep/product/index.md
    - LuatOS资料: https://docs.openluat.com/air780ep/luatos/
    - AT资料: https://docs.openluat.com/air780ep/at/
  - Air780EPS:
    - 简介: air780eps/index.md
    - 产品手册: air780eps/product/index.md
    - LuatOS资料: https://docs.openluat.com/air780eps/luatos/
    - AT资料: https://docs.openluat.com/air780eps/at/
  - Air780EX:
    - 简介: air780ex/index.md
    - 产品手册: air780ex/product/index.md
    - LuatOS资料: https://docs.openluat.com/air780ex/luatos/
    - AT资料: https://docs.openluat.com/air780ex/at/
  - Air724UG:
    - 简介: air724ug/index.md
    - 产品手册: air724ug/product/index.md
    - LuatOS资料: https://docs.openluat.com/air724ug/luatos/
    - AT资料: https://docs.openluat.com/air724ug/at/
    - USB驱动安装: https://docs.openluat.com/air724ug/driver/
  - Air201:
    - 简介: air201/index.md
    - 产品手册: air201/product/index.md
    - LuatOS资料: https://docs.openluat.com/air201/luatos/
  - Air780EG:
    - 简介: air780eg/index.md
    - 产品手册: air780eg/product/index.md
    - LuatOS资料: https://docs.openluat.com/air780eg/luatos/
    - AT资料: https://docs.openluat.com/air780eg/at/
  - 卫星定位模组: gnss.md
  - DTU: https://docs.openluat.com/dtu/
  - 增值服务: web.md
  - 技术博客: https://docs.openluat.com/blog/
  - 问答中心: https://chat.openluat.com/
  - 官网: https://www.openluat.com/
  - 文档共建: askforhelp.md

