INHERIT: ../base.yml
site_name: 合宙模组资料中心

nav:
  - 选型手册: product_manual/index.md
  - Air780E: air780e/index.md
  - Air780EP: air780ep/index.md
  - Air780EPS: air780eps/index.md
  - Air780EG: air780eg/index.md
  - Air201: air201/index.md
  - 问答中心: https://chat.openluat.com/
  - 合宙官网: https://www.openluat.com/
