INHERIT: ../base.yml
site_name: 合宙模组资料中心

meta:
  author: 上海合宙通信科技有限公司

nav:
  - 产品手册: product.md
  - Air780E:   https://docs.openluat.com/air780e/
  - Air700:    https://docs.openluat.com/air700/
  - Air780EQ:  https://docs.openluat.com/air780eq/
  - Air780EP:  https://docs.openluat.com/air780ep/
  - Air780EPS: https://docs.openluat.com/air780eps/
  - Air780EX:  https://docs.openluat.com/air780ex/
  - Air724UG:  https://docs.openluat.com/air724ug/
  - Air201:    https://docs.openluat.com/air201/
  - Air780EG:  https://docs.openluat.com/air780eg/
  - 卫星定位模组: https://docs.openluat.com/gnss/
  - DTU: https://docs.openluat.com/dtu/
  - 增值服务: https://docs.openluat.com/web/
  - 技术博客: https://docs.openluat.com/blog/
  - 问答中心: https://chat.openluat.com/
  - 官网: https://www.openluat.com/
  - 文档共建: https://docs.openluat.com/askforhelp/

