
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: zh
  highlightjs: true
  custom_dir: custom_theme
  #navigation_depth: 3
  features:
    #- announce.dismiss
    #- content.action.edit
    #- content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    #- content.footnote.tooltips
    #- content.tabs.link
    #- content.tooltips
    #- header.autohide
    #- navigation.expand
    #- navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.tracking
    # - navigation.path
    #- search.highlight
    #- search.share
    #- search.suggest
    #- toc.follow
    #- toc.integrate

plugins:
  - search:
      lang: zh

#repo_url: https://gitee.com/openLuat/luatos-doc-pool
copyright: Copyright (c) 2019-2024 openLuat & AirM2M

markdown_extensions:
  - attr_list